fix: istanbul-lib-source-maps to preserve implicit else when sourceps are used
istanbuljs/istanbuljs pull request #706
Opened 2022-11-04 13:40 UTC by AriPerkkio

- Fixes #705 

Tested the fix with reproduction case from downstream (https://github.com/vitest-dev/vitest/issues/2239) by modifying `./node_modules/istanbul-lib-source-maps/lib/transformer.js` on the fly. 

```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |       50 |     100 |     100 |                   
 cov.js   |     100 |       50 |     100 |     100 | 2                 
----------|---------|----------|---------|---------|-------------------

```

2022-11-04 13:43 UTC, AriPerkkio commented on packages/istanbul-lib-source-maps/lib/transformer.js
> +                }
For reference:

https://github.com/istanbuljs/istanbuljs/blob/fb8cb4bb99c9e5d36c8b011338d2ab5d3c72ff9c/docs/raw-output.md?plain=1#L49

https://github.com/istanbuljs/istanbuljs/blob/fb8cb4bb99c9e5d36c8b011338d2ab5d3c72ff9c/docs/raw-output.md?plain=1#L52

https://github.com/istanbuljs/istanbuljs/blob/fb8cb4bb99c9e5d36c8b011338d2ab5d3c72ff9c/packages/istanbul-reports/lib/html/annotator.js#L147-L154

2022-12-10 17:01 UTC, adrian-burlacu-software commented
@AriPerkkio
Thank you, I appreciate this! Felt pretty embarrassed trying to find all the spots that needed to update downstream.

2023-04-24 14:54 UTC, carpie commented
Hello! Is there a timeline for this to be merged? We're hitting this issue as well with cypress code coverage on instrumented code with source maps.  Thanks!

2023-04-24 16:01 UTC, AriPerkkio commented
Istanbul projects are not that active anymore so updates may take long time - if ever. 

If you have access to `coverageMap` in your Cypress setup you can apply same work-around that Vitest uses to patch these implicit else's: https://github.com/vitest-dev/vitest/pull/2275/files#diff-a0a730c31ce78cf1c3cb20d55daa7167ff57fa8e062df213c6eeb918582d1cb5R244-R272

2024-06-30 20:31 UTC, SimenB requested changes
Since no old tests are changed, I assume this is fine 🙂

CI seems to be failing, tho

2024-07-01 07:09 UTC, SimenB commented
Right, that makes sense 👍

2024-07-01 07:09 UTC, SimenB approved these changes

2024-07-01 07:09 UTC, merged

2024-07-01 07:34 UTC, SimenB commented
https://github.com/istanbuljs/istanbuljs/releases/tag/istanbul-lib-source-maps-v5.0.5

2024-07-01 12:26 UTC, AriPerkkio commented
This change is actually breaking some test cases in Vitest - tests that we didn't have in 2022 when this PR was created 😅 

`source` here can now be `null`:

https://github.com/istanbuljs/istanbuljs/blob/41d98a7c2a852a9cf8e49c087706bf7f71a91d4a/packages/istanbul-lib-source-maps/lib/transformer.js#L105

Which ends up breaking here:

https://github.com/istanbuljs/istanbuljs/blob/41d98a7c2a852a9cf8e49c087706bf7f71a91d4a/packages/istanbul-lib-source-maps/lib/transformer.js#L120-L127

https://github.com/istanbuljs/istanbuljs/blob/41d98a7c2a852a9cf8e49c087706bf7f71a91d4a/packages/istanbul-lib-source-maps/lib/transform-utils.js#L7-L9


https://github.com/vitest-dev/vitest/actions/runs/9743759050/job/26887930830?pr=6014

```
TypeError: Cannot read properties of undefined (reading 'replace')
 ❯ getUniqueKey ../../node_modules/.pnpm/istanbul-lib-source-maps@5.0.5/node_modules/istanbul-lib-source-maps/lib/transform-utils.js:8:21
 ❯ getMappedCoverage ../../node_modules/.pnpm/istanbul-lib-source-maps@5.0.5/node_modules/istanbul-lib-source-maps/lib/transformer.js:121:25
 ❯ ../../node_modules/.pnpm/istanbul-lib-source-maps@5.0.5/node_modules/istanbul-lib-source-maps/lib/transformer.js:105:40
 ❯ SourceMapTransformer.processFile ../../node_modules/.pnpm/istanbul-lib-source-maps@5.0.5/node_modules/istanbul-lib-source-maps/lib/transformer.js:64:38
 ❯ SourceMapTransformer.transform ../../node_modules/.pnpm/istanbul-lib-source-maps@5.0.5/node_modules/istanbul-lib-source-maps/lib/transformer.js:137:38
 ❯ MapStore.transformCoverage ../../node_modules/.pnpm/istanbul-lib-source-maps@5.0.5/node_modules/istanbul-lib-source-maps/lib/map-store.js:217:16
```

2024-07-01 12:38 UTC, AriPerkkio commented
I can look for a fix tomorrow. Most of our test cases are passing just fine so it looks like some kind of edge case. Maybe most users won't run into it.

2024-07-01 12:49 UTC, SimenB commented
Can see if we have any failing tests as well: https://github.com/jestjs/jest/pull/15156

2024-07-01 18:03 UTC, AriPerkkio commented
Alright fix ready in https://github.com/istanbuljs/istanbuljs/pull/789. I've tested it with Vitest.